#!/bin/bash
BINDIR=$(dirname `readlink -f $0`) && export BINDIR=${BINDIR}/bin
export echo="${BINDIR}/echo0"

# version #
export TEMP2_VERSION=2.01

# usage #
usage (){
$echo 5 "TEMP2 -- Version ${TEMP2_VERSION}"
$echo 5 "      -- germline and somatic transposon insertion and deletion analysis\n"
$echo 4 "usage:"
$echo 0 "$0 insertion -h\t# for germline and somatic transposon insertion\n"
$echo 1 "$0 insertion2 -h\t# for only germline transposon insertion\n"
$echo 6 "$0 deletion -h\t\t# for transposon deletion"
}

# run #
if [ $# -lt 1 ];then
	usage
	exit 1
fi
case ${1} in
	insertion)
		shift && bash ${BINDIR}/TEMP2_insertion.sh "$@";;
	insertion2)
		shift && bash ${BINDIR}/TEMP2_insertion2.sh "$@";;
	deletion)
		shift && bash ${BINDIR}/TEMP2_deletion.sh "$@";;
	*)
		usage;;
esac

